# use kubectl -k (or kustomize) to map files from the workspace
# into configmaps for a container
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ns.yaml
  - deployment.yaml
  - staging-certificate.yaml
  - service.yaml
  - ingress.yaml