apiVersion: cert-manager.io/v1 
kind: Certificate
metadata:
  name: tls-cert-prod
  namespace: kim
spec:
  secretName: tls-secret-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kimlauritsen.com
  dnsNames:
  - kimlauritsen.org
  - kimlauritsen.com