apiVersion: cert-manager.io/v1 
kind: Certificate
metadata:
  name: tls-cert-staging
  namespace: kim
spec:
  secretName: tls-secret-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: kimlauritsen.com
  dnsNames:
  - kimlauritsen.org
  - kimlauritsen.com